### ISSUE TITLE
Soft98 Ad Blocker — کد حذف تبلیغات سافت98

### ISSUE THREAD

**Issue by DRSDavidSoft** [DRSDavidSoft/user-scripts#1]
## Moved all Soft98-related ad-blocking discussions to PersianBlocker:
https://github.com/MasterKia/PersianBlocker/issues/40

> Please see the statement here: https://github.com/MasterKia/PersianBlocker/issues/40#issuecomment-3130400283

> https://github.com/MasterKia/PersianBlocker/issues/28#issuecomment-1205481235

### Userscript info:

<details><summary><strong>Outdated information</strong></summary>

**Install:** [⚙ **soft98_ad-unblocker.user.js**](https://github.com/DRSDavidSoft/user-scripts/raw/master/soft98_ad-unblocker.user.js)

**راهنمای نصب فارسی:**
برای حذف تبلیغات سافت 98، ابتدا افزونه [Tampermonkey](https://www.google.com/search?q=tampermonkey+extension&hl=fa) را مخصوص مرورگر خود از لینک‌های زیر دانلود نمایید:  
<a href="https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=fa"><img src="https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Chrome_icon_%28September_2014%29.svg" width=16 height=16 /> Chrome — <b>Tampermonkey</b>برای گوگل کروم</a>  
<a href="https://addons.mozilla.org/fa/firefox/addon/tampermonkey/"><img src="https://upload.wikimedia.org/wikipedia/commons/a/a0/Firefox_logo%2C_2019.svg" width=16 height=16 /> Firefox — <b>Tampermonkey</b> برای موزیلا فایرفاکس</a>  
بعد از نصب این افزونه، کافیست که روی لینک: [📁 **نصب کد حذف تبلیغات سافت ۹۸**](https://github.com/DRSDavidSoft/user-scripts/raw/master/soft98_ad-unblocker.user.js) کلیک کنید، سپس باید در پنجره یا تب باز شده روی کلید <kbd>**Install**</kbd> کلیک کنید.

**Features:**
- Prevents Soft98 from disabling download links
- Removes **all** ads on the website
- Restores any links, if any

</details>

**Status:** ❌ Currently not working

### Description in detail:
- https://github.com/NanoMeow/QuickReports/issues/514#issuecomment-575426935
- https://github.com/uBlockOrigin/uAssets/issues/3011

### Related issues:
- https://github.com/NanoAdblocker/NanoFilters/issues/64
- https://github.com/AdguardTeam/AdguardFilters/issues?q=soft98
   - https://github.com/AdguardTeam/AdguardFilters/issues/23360#issuecomment-444678267
   - https://github.com/AdguardTeam/AdguardFilters/issues/47866
   - https://github.com/AdguardTeam/AdguardFilters/issues/22177
   - https://github.com/AdguardTeam/AdguardFilters/issues/17796
   - https://github.com/AdguardTeam/AdguardFilters/issues/102643
   - https://github.com/AdguardTeam/AdGuardExtra/issues/204
   - https://github.com/AdguardTeam/AdGuardExtra/issues/348
   - https://github.com/AdguardTeam/AdguardFilters/pull/83659 (unfortunately removed)
   - https://github.com/AdguardTeam/AdguardFilters/issues/83051 (Possible userscript fix?)
   - https://github.com/AdguardTeam/AdguardFilters/issues/105818
   - https://github.com/AdguardTeam/AdguardFilters/issues/126252
   - https://github.com/AdguardTeam/AdguardFilters/issues/209334
- https://github.com/mboveiri/ublock-iran/issues/2
- https://github.com/farrokhi/adblock-iran/issues/17
- https://github.com/reek/anti-adblock-killer/issues/4100
- https://github.com/SlashArash/adblockfa/issues/16#issue-946308787
- https://github.com/nimasaj/uBOPa/issues/6
- https://github.com/reek/anti-adblock-killer/issues/4120
- https://github.com/reek/anti-adblock-killer/issues/4456
- https://github.com/uBlockOrigin/uAssets/issues/3011
- https://github.com/uBlockOrigin/uAssets/issues/10883
   - https://github.com/uBlockOrigin/uAssets/commit/1461af6db50759af99c20589ba47e25c78068595
- https://github.com/brave/adblock-lists/issues/730
- https://github.com/bogachenko/fuckfuckadblock/issues/253
- https://github.com/MasterKia/PersianBlocker/issues/23
- https://github.com/MasterKia/PersianBlocker/issues/28
- https://github.com/MasterKia/PersianBlocker/issues/311

### Notes
- since most filter maintainers are removing soft98-related entries from their lists, now in addition to blocking the "toast notification", this script will _actually also remove the ads_, too.
- if the removal of these useless ads are successful, the Soft98's logo in header is enhanced (changed with a custom pirate-flag one).

**Comment by MasterKia** [comment]
درود دیوید عزیز.
من تقریباً ده سال پیش با شما آشنا شدم؛ همون زمانایی که یه اسکریپت واسه حذف تبلیغات بلاگفا نوشته بودید و اسکریپتتون خیلی مشهور شده بود و همه جا پیچیده بود.
نمیدونم هنوز اون اسکریپت کار میکنه یا نه اما یادمه هی بلاگفا اسکریپت شما رو مسدود میکرد بعد شما دوباره نسخه جدید براش میدادی.
حالا الان از 10 سال پیش که دیگه تبلیغات تو سایت ها چندین برابر تشدید شده و بدتر شده.

نمیدونم چرا ، اما همیشه ارادت و احترام خاصی به شما داشتم شاید چون تو اون بازه زمانی حس میکردم تونستید یک تنه در برابر بلاگفا در بیایید و قد علم کنید.
خیلی خوشحال شدم که میون جستجو هام ، ریپوی شما رو پیدا کردم و برام تجدید خاطره شد.
امیدوارم هر جا که هستی موفق باشی و هر کاری که میکنی توش بهترین باشی.
با کمال احترام.

**Comment by DRSDavidSoft** [comment]
درود و سلام به @MasterKia عزیز،

از خواندن پیام شما بسیار خوشحال شدم و از اینکه بنده‌رو در خاطره خود داشتید متشکرم! 😄 

[اسکریپت حذف تبلیغات بلاگفا و رزبلاگ](https://blog.refoua.me/post/ads-remover-script/?lang=fa
)، برای خودم هم یکی از اولین چالش‌های جالبی بود که با وجود تنش بین من و مدیران این سایت‌ها به‌وجود آمده بود، و من از اینکه راهکاری جهت حذف تبلیغات مزخرف این‌گونه وبلاگ‌ها ارائه بدم بسیار لذت می‌بردم. به تأیید نقل قول شما، از آن زمان وضعیت تبلیغات این سایت‌ها به مرور بدتر و بدتر هم شده، وتبلیغات هرچه مزخرف‌تر از گذشته را قرار می‌دهند.

به مرور کاربران این سرویس‌ها کمتر شده؛ البته من همچنان این اسکریپت‌رو مینتین می‌کنم، و کاربران این سرویس‌های وبلاگدهی نیز با بنده در ارتباط هستند. در آخرین به‌روز رسانی، اسکریپت رو به مرحله‌ای رسوندم که مدیران بلاگفا (آقای [علیرضا شیرازی](https://twitter.com/alirezashirazi?lang=fa)) و مدیران رزبلاگ (آقای محمد جواد صداقت‌پور) و برنامه‌نویسان آن‌ها دیگر توانایی، حوصله و یا علاقه‌ی از بین بردن کد بنده رو ندارند، و تنها با چک کردن عبارت‌هایی مانند زیر، از اینکلود شدن اسکریپت جلوگیری می‌کنند!
 `ads-remover` و کلمه‌ی `Refoua`
البته راه مقابله با این روش هم ساده است و با استفاده از دامین‌های مختلف به‌راحتی می‌توان آن را دور زد.

بیشترین مورد استفاده این اسکریپت هم برای استفاده خودم بود، چون در آن زمان خیلی استفاده از افزونه‌های حذف تبلیغات بین کاربران رایج نبود. اکنون من استفاده از این افزونه رو بسیار به همه توصیه می‌کنم:
uBlockOrigin
که در صورت نصب و فعالسازی فیلتر‌های فارسی (مانند [این نمونه](https://github.com/farrokhi/adblock-iran/blob/master/filter.txt) که من در نوشتن آن سهیم هستم) به‌هیچ‌وجه دیگر تبلیغات این سرویس‌دهنده‌ها نمایش داده نخواهد شد، و نیازی به استفاده از اسکریپت بنده نیست.

**اما در مورد تبلیغات سافت98**، موضوع هم همینگونه است (البته اخیراً حداقل تبلیغاتی که قبول می‌کنند مثل سابق مزخرف نیست، و در حد بنر ساده است). همناطور که در ارتباط با مدیر این سایت (آقای سالار) هم بیان کردم، من هیچ علاقه‌ای به کاپریلا، پادویش و... نیز در سایت ایشان ندارم، و به‌علت عدم کلیک بر روی این موارد، اسکریپت این ریپو رو نوشتم که این تبلیغات رو هم حذف کنه.

نکته جالب این هست که ایشون هم مثل مدیران سرویس‌های وبلاگ‌دهی، به دنبال روشی جهت جلوگیری از حذف تبلیغات بودند، و برای افزونه‌های معروفی مانند ادگارد کدهای مخصوص جلوگیری نوشته بودند، و در کمال تعجب، اشاره به اسکریپت کوچک بنده نیز شامل کد‌های جلوگیری ایشان بود!

با توجه به پیام بسیار نامحترمانه‌ای که سایت برای کاربران با افزونه‌های حذف تبلیغات نشان می‌دهد (مبنی بر این‌که جهت نمایش لینک‌های دانلود، بایستی افزونه را غیر فعال کنید)، من تصمیم گرفتم که مانند گذشته، کدی بنویسم که امکان جلوگیری از آن تا حد زیادی وجود نداشته باشد.

نتیجه آن‌هم همین اسکریپت است که تا این زمان کار می‌کند، و سافت98 پیشرفتی در جلوگیری از اجرای آن نداشته. که بسیار برای بنده جالب است! 😎  با توجه به اینکه افزونه یوبلاک و ادگارد به خوبی قابلیت از کار انداختن کد سافت 98 به تنهایی را نداشتند، این اسکریپت می‌تواند به‌صورت کمکی هم در کنار این دو استفاده شود تا نه تبلیغات نشان داده شود، و نه لینک‌ها از کار بیفتند. استفاده کاربران از کدهایی که من می‌نویسم هم بسیار برای بنده جذاب است.

به هر حال، از نوشتن پیام طولانی عذرخواهی می‌کنم، و برای شما هم آرزوی موفقیت و تندرستی دارم، امیدوارم پاینده باشید!
از این که لطف نمودید و پیام ثبت کردید از شما متشکرم 🙏🏻

**Comment by MasterKia** [comment]
درود بر شما.
با توجه به اینکه افزونه uBlock origin از Custom script ها پشتیبانی میکنه (مثل [این](https://github.com/abrahamjuliot/ublock-origin-abf#ublock-origin-setup) مورد و [این ](https://www.reddit.com/r/uBlockOrigin/comments/h9r5z8/comment/fuygvp4/?utm_source=share&utm_medium=web2x&context=3)مورد)، به نظر شما میشه اسکریپتی که برای سافت 98 نوشتید رو از طریق افزونه uBO به کار بگیریم و TamperMonkey رو از دور خارج کنیم؟

من مواردی که [اینجا](https://github.com/abrahamjuliot/ublock-origin-abf#ublock-origin-setup) ذکر شده بود رو با رعایت جزییات، با اسکریپت شما منطبق کردم و تلاش کردم که راهش بندازم اما نتیجه ای نگرفتم و گمان کردم که احتمالاً نیاز به اعمال تغییراتی از جانب شما در اسکریپت باشه تا با سیستم Script injection افزونه uBO سازگار در بیاد.

و جدای از اون، با توجه به اینکه افزونه uBO یک سری [کتابخونه های داخلی](https://github.com/gorhill/uBlock/wiki/Resources-Library) برای مقابله با تبلیغاتِ پیشرفته تر (و علی الخصوص خنثی سازی «ضد مسدود کننده تبلیغات») داره، میشه ازون کتابخونه ها برای مقابله با سافت98 بهره گرفت؟

**Comment by MasterKia** [comment]
Related issue: https://reports.adblockplus.org/a253a100-3f0a-4c5b-a314-38850cf5496b

**Comment by MasterKia** [comment]
Could you verify whether the script is still working?

**Comment by DRSDavidSoft** [comment]
@MasterKia Thanks for the reports, it's just a small class name change. I'm working on the cat side of this cat and mouse game, I'll update the script in a bit. Thanks!

**Comment by Mds92** [comment]
nowadays, the scripts not work

**Comment by DRSDavidSoft** [comment]
@Mds92 Sorry I haven't updated the script in a while now, the last working solution was by @MasterKia. I will work on another solution that will be integrated into the https://github.com/MasterKia/PersianBlocker repo soon.

I have been very busy with work (and the recent power outages in the city, I'm afraid)

**Comment by DRSDavidSoft** [comment]
Moving all efforts to https://github.com/MasterKia/PersianBlocker/issues/40.
